# Generated by Django 5.0.2 on 2025-03-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_payment_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='verification_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Código de Verificación'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='Archivo PDF'),
        ),
    ]
