# Generated by Django 5.0.2 on 2025-02-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_counters', '0002_paymentlink_delete_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentlink',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='payer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='payer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
