# Generated by Django 5.0.2 on 2025-02-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_counters', '0003_alter_paymentlink_options_paymentlink_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='reference_id',
            field=models.CharField(default='temp_ref', max_length=100, unique=True),
        ),
    ]
