# Generated by Django 5.0.2 on 2025-02-23 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_counters', '0006_alter_paymentlink_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentlink',
            options={'ordering': ['-created_at'], 'verbose_name': 'Link de Pago', 'verbose_name_plural': 'Links de Pago'},
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expira en'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='payer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email del Pagador'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='payer_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre del Pagador'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='payment_link',
            field=models.URLField(verbose_name='Link de Pago'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('cancelled', 'Cancelado'), ('expired', 'Expirado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=100, unique=True, verbose_name='Número de Comprobante')),
                ('secret_code', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Código Secreto')),
                ('pdf_file', models.FileField(upload_to='receipts/', verbose_name='Archivo PDF')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('payment_link', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='checkout_counters.paymentlink', verbose_name='Link de Pago')),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
                'ordering': ['-generated_at'],
            },
        ),
    ]
