# Generated by Django 5.0.2 on 2025-02-25 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_counters', '0009_make_payer_name_nullable'),
    ]

    operations = [
    ]
