# Generated by Django 5.0.2 on 2025-02-25 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_counters', '0010_auto_20250225_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='mercadopago_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID de Mercado Pago'),
        ),
        migrations.CreateModel(
            name='ReceiptVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(max_length=20, unique=True, verbose_name='Código de Verificación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='checkout_counters.receipt', verbose_name='Comprobante')),
            ],
            options={
                'verbose_name': 'Verificación de Comprobante',
                'verbose_name_plural': 'Verificaciones de Comprobantes',
                'ordering': ['-created_at'],
            },
        ),
    ]
