# Generated by Django 5.0.2 on 2025-02-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_counters', '0011_receipt_mercadopago_id_receiptverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='mercadopago_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de Mercado Pago'),
        ),
    ]
