# Generated by Django 5.0.2 on 2025-02-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_counters', '0012_alter_receipt_mercadopago_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='payer_first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Pagador'),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='payer_last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido del Pagador'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='payer_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Completo del Pagador'),
        ),
    ]
