# Generated by Django 4.2.19 on 2025-02-21 18:05

from django.db import migrations, models
import django.db.models.deletion
import forgeapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('url', models.URLField(verbose_name='URL del Proyecto')),
                ('documentation_url', models.URLField(blank=True, null=True, verbose_name='URL de Documentación')),
                ('git_repository', models.URLField(blank=True, null=True, verbose_name='Repositorio Git')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Aplicación',
                'verbose_name_plural': 'Aplicaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Calculadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre/Referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Suma Total de Items')),
                ('margen', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Margen de Ganancia')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento por Pago Anual')),
                ('total_anual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Anual con Descuento')),
                ('cuota_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Cuota Mensual')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('costo_mercado', models.DecimalField(blank=True, decimal_places=2, help_text='Costo promedio de desarrollo de la aplicación en el mercado', max_digits=10, null=True, verbose_name='Costo promedio en el mercado')),
                ('tiempo_mercado', models.DecimalField(blank=True, decimal_places=1, help_text='Tiempo promedio de desarrollo en el mercado en semanas', max_digits=5, null=True, verbose_name='Tiempo promedio en el mercado (semanas)')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculadoras', to='forgeapp.application', verbose_name='Aplicación')),
            ],
            options={
                'verbose_name': 'Calculadora',
                'verbose_name_plural': 'Calculadoras',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, validators=[forgeapp.models.validate_rut], verbose_name='RUT')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Empresa')),
                ('company_rut', models.CharField(blank=True, max_length=12, validators=[forgeapp.models.validate_rut], verbose_name='RUT Empresa')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('pending', 'Pendiente')], default='active', max_length=20, verbose_name='Estado')),
                ('nationality', models.CharField(choices=[('chilena', 'Chilena'), ('extranjera', 'Extranjera')], default='chilena', max_length=20, verbose_name='Nacionalidad')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('cancelled', 'Cancelada'), ('pending', 'Pendiente'), ('expired', 'Expirada')], default='pending', max_length=20, verbose_name='Estado')),
                ('payment_type', models.CharField(choices=[('monthly', 'Mensual'), ('annual', 'Anual')], default='monthly', max_length=20, verbose_name='Tipo de Pago')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('auto_renewal', models.BooleanField(default=False, verbose_name='Autorenovación')),
                ('renewal_notes', models.TextField(blank=True, verbose_name='Notas de Renovación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items_detail', models.JSONField(blank=True, default=dict, verbose_name='Detalles de Items')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forgeapp.application')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='forgeapp.client')),
                ('original_calculator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_subscriptions', to='forgeapp.calculadora')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('calculadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='forgeapp.calculadora')),
            ],
            options={
                'verbose_name': 'Item de Cálculo',
                'verbose_name_plural': 'Items de Cálculo',
            },
        ),
        migrations.AddField(
            model_name='calculadora',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculadoras', to='forgeapp.client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='application',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_applications', to='forgeapp.client', verbose_name='Propietario'),
        ),
        migrations.CreateModel(
            name='ApplicationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='Clave')),
                ('value', models.TextField(verbose_name='Valor')),
                ('field_type', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('url', 'URL'), ('password', 'Contraseña')], default='text', max_length=20, verbose_name='Tipo de Campo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_encrypted', models.BooleanField(default=False, verbose_name='Está Encriptado')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='forgeapp.application', verbose_name='Aplicación')),
            ],
            options={
                'verbose_name': 'Configuración de Aplicación',
                'verbose_name_plural': 'Configuraciones de Aplicación',
                'ordering': ['key'],
                'unique_together': {('application', 'key')},
            },
        ),
    ]
