# Generated by Django 5.0.2 on 2025-02-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgeapp', '0002_add_subscription_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva'), ('cancelled', 'Cancelada'), ('pending', 'Pendiente'), ('expired', 'Expirada')], default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
