# Generated by Django 5.0.2 on 2025-02-22 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forgeapp', '0003_alter_subscription_status'),
        ('forgeapp', '0007_alter_subscription_status'),
    ]

    operations = [
    ]
