# Generated by Django 5.0.2 on 2025-02-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgeapp', '0008_merge_20250222_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], default='inactive', max_length=20, verbose_name='Estado'),
        ),
    ]
