# Generated by Django 5.0.2 on 2025-02-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgeapp', '0009_remove_pending_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Último Pago'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Próximo Pago'),
        ),
    ]
