# Generated by Django 5.0.2 on 2025-02-22 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgeapp', '0010_add_payment_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='original_calculator',
        ),
        migrations.AddField(
            model_name='subscription',
            name='calculadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='forgeapp.calculadora'),
        ),
    ]
