# Generated by Django 5.0.2 on 2025-02-25 03:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgeapp', '0011_rename_subscription_calculator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1, message='El precio debe ser mayor a 0')], verbose_name='Precio'),
        ),
    ]
