# Generated by Django 5.0.2 on 2025-02-26 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgeapp', '0012_alter_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='accept_marketing',
            field=models.BooleanField(default=False, verbose_name='Acepta Marketing'),
        ),
        migrations.AddField(
            model_name='client',
            name='contract_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado'), ('none', 'Sin Contrato')], default='none', max_length=20, verbose_name='Estado del Contrato'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='accept_marketing',
            field=models.BooleanField(default=False, verbose_name='Acepta Marketing'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva'), ('cancelled', 'Cancelada'), ('expired', 'Expirada'), ('pending', 'Pendiente')], default='inactive', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='ServiceContractToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.IntegerField(verbose_name='ID de Aplicación')),
                ('subscription_type', models.CharField(choices=[('monthly', 'Mensual'), ('annual', 'Anual')], max_length=20, verbose_name='Tipo de Suscripción')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('expires_at', models.DateTimeField(verbose_name='Fecha de Expiración')),
                ('used', models.BooleanField(default=False, verbose_name='Usado')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Uso')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_tokens', to='forgeapp.client')),
            ],
            options={
                'verbose_name': 'Token de Contrato',
                'verbose_name_plural': 'Tokens de Contratos',
                'ordering': ['-created_at'],
            },
        ),
    ]
