# Generated by Django 5.0.2 on 2025-02-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgeapp', '0013_client_accept_marketing_client_contract_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecontracttoken',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio'),
        ),
    ]
