# Generated by Django 5.0.2 on 2025-02-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgeapp', '0014_servicecontracttoken_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(editable=False, max_length=200, verbose_name='Nombre Completo'),
        ),
    ]
