# Generated by Django 5.2.7 on 2025-11-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgeapp', '0016_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='end_date',
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancelled_at',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Cancelación'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_rut',
            field=models.CharField(blank=True, max_length=12, verbose_name='RUT Empresa'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='auto_renewal',
            field=models.BooleanField(default=True, verbose_name='Autorenovación'),
        ),
    ]
