# Generated by Django 5.2.3 on 2025-11-04 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgeapp', '0017_remove_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='last_payment_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='next_payment_date',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activa'), ('inactive', 'Inactiva'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_date', models.DateField(verbose_name='Fecha Esperada de Pago')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago Real')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado')], default='pending', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_events', to='forgeapp.subscription', verbose_name='Suscripción')),
            ],
            options={
                'verbose_name': 'Evento de Pago',
                'verbose_name_plural': 'Eventos de Pago',
                'ordering': ['-expected_date'],
            },
        ),
    ]
