# Generated by Django 5.2.3 on 2025-11-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgeapp', '0018_remove_subscription_last_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
    ]
