# Generated by Django 5.2.8 on 2025-12-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgeapp', '0019_alter_subscription_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecontracttoken',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='Código de Autorización'),
        ),
        migrations.AddField(
            model_name='servicecontracttoken',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Firma'),
        ),
        migrations.AddField(
            model_name='servicecontracttoken',
            name='signed_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre Firmante'),
        ),
        migrations.AddField(
            model_name='servicecontracttoken',
            name='signed_rut',
            field=models.CharField(blank=True, max_length=12, verbose_name='RUT Firmante'),
        ),
        migrations.AddField(
            model_name='servicecontracttoken',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de Firma'), ('signed', 'Firmado'), ('expired', 'Expirado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
