# Generated by Django 5.2.8 on 2025-12-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgeapp', '0020_add_contract_authorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecontracttoken',
            name='currency',
            field=models.CharField(choices=[('CLP', 'Pesos Chilenos (CLP)'), ('USD', 'Dólares (USD)')], default='CLP', max_length=3, verbose_name='Moneda'),
        ),
    ]
