# Generated by Django 5.2.7 on 2025-12-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgeapp', '0021_add_currency_to_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculadora',
            name='currency',
            field=models.CharField(choices=[('CLP', 'Pesos Chilenos (CLP)'), ('USD', 'Dólares (USD)')], default='CLP', max_length=3, verbose_name='Moneda'),
        ),
    ]
