# Generated by Django 5.2.7 on 2025-12-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forgeapp', '0023_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='phone',
        ),
    ]
