# Generated by Django 5.2.7 on 2025-12-30 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgeapp', '0024_remove_contactmessage_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('start_time', models.TimeField(verbose_name='Hora de Inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de Fin')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('meeting_link', models.URLField(blank=True, max_length=500, verbose_name='Link de Reunión')),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='scheduled', max_length=20, verbose_name='Estado')),
                ('is_blocked', models.BooleanField(default=False, help_text='Horario bloqueado manualmente', verbose_name='Bloqueado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=500, verbose_name='Link de Reunión'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_message', to='forgeapp.appointment', verbose_name='Cita Agendada'),
        ),
    ]
