# Generated by Django 5.2.7 on 2026-01-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgeapp', '0025_appointment_contactmessage_meeting_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecontracttoken',
            name='signed_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contracts/signed/', verbose_name='PDF Firmado'),
        ),
    ]
