# Generated by Django 5.2.7 on 2026-02-04 18:31

import forgeapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgeapp', '0026_add_signed_pdf_to_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='client',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[forgeapp.models.validate_rut], verbose_name='RUT'),
        ),
    ]
